language: csharp

mono: 5.2.0
dotnet : 5.1.100

install:
  - mozroots --import --sync
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
matrix:
  include:
    - os: linux
      sudo: required

script: 
  - dotnet --info
  - dotnet tool restore
  - dotnet build -c Release
  - dotnet test --no-restore --no-build -c Release tests/FSharp.Control.Reactive.Tests.fsproj
  - dotnet pack --no-restore -c Release --include-symbols

branches:
  except:
    - gh-pages
