image: Visual Studio 2019
version: '{build}'
clone_depth: 10
environment:
    CLI_VERSION: 5.0.100
init:
  - git config --global core.autocrlf input
build_script:
  - ps: |
      .\build.ps1
      if ($lastexitcode -ne 0){ exit $lastexitcode }
test: off
artifacts:
  - path: bin\*.nupkg
deploy:
- provider: Environment
  name: FSharp.Control.Reactive
  on:
    APPVEYOR_REPO_TAG: true
