name: NuGet Publish

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
      - name: Set env
        if: startsWith( github.ref, 'refs/tags/v' )
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION=${RELEASE_VERSION}" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "Version=${RELEASE_VERSION:1}" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Restore
        run: dotnet tool restore
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test --no-build -c Release tests
      - name: Pack
        run: dotnet pack --no-restore -c Release --include-symbols -o bin
      - name: Push
        if: startsWith( github.ref, 'refs/tags/v' )
        run: dotnet nuget push bin\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }}
